version: 0.0
os: linux
files:
  - source: /firstpage.html
    destination: /WebExampleV1/WebContent/
hooks:
  BeforeInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
